name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-17"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "postgresql://mediumBlogs_owner:B80gysvwoJEO@ep-nameless-mud-a5bt54m2-pooler.us-east-2.aws.neon.tech/mediumBlogs?sslmode=require"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1